apiVersion: v1
kind: Service
metadata:
  name: projects-postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: projects-postgres
  ports:
    - port: 5432
      targetPort: 5432
