version: "3"
services:
  projects-postgres:
    image: postgres
    container_name: 'projects-postgres'
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_ENCODING=UTF8'

  project-management:
    image: mmbarek/project-management-service
    depends_on:
      - projects-postgres
    ports:
      - '8020:8020'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
  postgresqldata:
    external: false
